gestionprojets/urls.py
from django.contrib import admin
from django.urls import path, include
from projects.views import home
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

app_name = "gestionprojects"

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("projects/", include('projects.urls')),
                  path("", home, name="home"),
                  path(
                      "login/",
                      views.LoginView.as_view(template_name='projects/login.html', redirect_authenticated_user=True),
                      name="login-page"
                  ),
                  path(
                      "logout/",
                      views.LogoutView.as_view(template_name='projects/logout.html', next_page='login-page'),
                      name="logout"
                  )
              ] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

projects/urls.py
from django.urls import path
from projects.views import add_project, add_tache, update_tache

app_name = "projects"

urlpatterns = [
                  path('add_project/', add_project, name='add-project'),
                  path('update_tache/<int:tache_id>', update_tache, name='update-tache'),
                  path('add_tache/<int:project_id>/', add_tache, name='add-tache'),
              ]

projects/models.py
from django.db import models


class Project(models.Model):
    STATUS_CHOICES = [
        ('EN_ATTENTE', 'En Attente'),
        ('EN_COURS', 'En Cours'),
        ('SUSPENDU', 'Suspendu'),
        ('TERMINE', 'Terminé'),
        ('EN_EVAL', 'En Évaluation'),
        ('EXPIRE', 'Expiré'),
    ]

    name = models.CharField(max_length=200)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='EN_ATTENTE')

    def __str__(self):
        return self.name


class Tache(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    number_order = models.IntegerField()
    description = models.TextField()
    date_end = models.DateField()
    checked = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.number_order} - {self.description}"

projects/forms.py
from django import forms
from .models import Project, Tache


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name']


class TacheForm(forms.ModelForm):
    class Meta:
        model = Tache
        fields = ["project", "number_order", "description", "date_end"]


class UpdateTacheForm(forms.ModelForm):
    class Meta:
        model = Tache
        fields = ["checked"]

projects/views.py
from django.shortcuts import render
from .forms import ProjectForm, TacheForm, UpdateTacheForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.http import JsonResponse, HttpResponseRedirect
from .models import Project, Tache
from django.shortcuts import get_object_or_404


# Create your views here.
@login_required()
def home(request):
    projects = Project.objects.prefetch_related('tache_set').all()
    return render(request, 'projects/index.html', {'projects': projects})


def login(request):
    return render(request, 'projects/login.html')


@login_required()
def add_project(request):
    submitted = False
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            # return JsonResponse({'status': 'success', 'project_id': project.id})
            return HttpResponseRedirect("/")
    else:
        form = ProjectForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'projects/add_project_form.html', {'form': form})


@login_required()
def add_tache(request, project_id):
    submitted = False
    if request.method == 'POST':
        form = TacheForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
    else:
        form = TacheForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'projects/add_tache_form.html', {'project': project_id})


@login_required()
@csrf_protect
def update_tache(request, tache_id):
    # return HttpResponseRedirect("/")
    submitted = False
    tache = get_object_or_404(Tache, id=tache_id)

    if request.method == 'POST':
        form = UpdateTacheForm(request.POST)
        if form.is_valid():
            tache.checked = not tache.checked
            tache.save()
    else:
        form = UpdateTacheForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'projects/index.html')

projects/templates/projects/add_project_form.html
{% extends 'projects/base.html' %}
{% block title %}Ajout de projet{% endblock %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <div class="frame m-4 p-4">
                    <div class="list w-75">
                        <div class="head">
                            <div class="title">Ajouter un projet</div>
                        </div>
                        <form action method="POST">
                            {% csrf_token %}
                            <div class="form-group mt-5 p-2">
                                <input id="name" type="text" name="name" class="form-control" required>
                                <label class="form-control-placeholder" for="name">Nom du projet</label>
                            </div>
                            <div class="form-group d-block float-right mt-2 mr-4 w-25">
                                <button type="submit" class="form-control btn btn-login rounded submit px-3">Ajouter</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        <div class="col-lg-2"></div>
    </div>
</div>
{% endblock %}

projects/templates/projects/add_tache_form.html
{% extends 'projects/base.html' %}
{% block title %}Ajout de tache{% endblock %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <div class="frame m-4 p-4">
                    <div class="list w-75">
                        <div class="head">
                            <div class="title">Ajouter une tâche</div>
                        </div>
                        <form action method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="project" value="{{ project }}">
                            <div class="form-group mt-5 p-2">
                                <input id="number_order" type="number" name="number_order" class="form-control" required>
                                <label class="form-control-placeholder" for="number_order">Numéro d'ordre</label>
                            </div>
                            <div class="form-group mt-5 p-2">
                                <input id="description" type="text" name="description" class="form-control" required>
                                <label class="form-control-placeholder" for="description">Description de la tâche</label>
                            </div>
                            <div class="form-group mt-5 p-2">
                                <input id="date_end" type="date" name="date_end" class="form-control" required>
                                <label class="form-control-placeholder" for="date_end">Date d'echéance</label>
                            </div>
                            <div class="form-group d-block float-right mt-2 mr-4 w-25">
                                <button type="submit" class="form-control btn btn-login rounded submit px-3">Ajouter</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        <div class="col-lg-2"></div>
    </div>
</div>
{% endblock %}

projects/templates/projects/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
  	<title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">

	</head>
	<body class="bg-home">
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" style="font-size: inherit" href="{% url 'home' %}">Gestion de Projet Personnel</a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                        <form class="nav-link" method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                            <button class="btn-logout" type="submit">Déconnexion</button>
                        </form>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    {% endblock %}
    {% block content %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

projects/templates/projects/index.html
{% extends 'projects/base.html' %}
{% block title %}Accueil{% endblock %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        {% for project in projects %}
        <div class="col-lg-4">
            <div class="frame m-2">
                <div class="list">
                    <div class="head">
                        <div class="title">{{ project.name }}</div>
                        <div class="subtitle">
                            Ajouter une tâche
                            <a class="add-tache-btn" href="{% url 'projects:add-tache' project.id %}"><img src="{% static 'images/plus.png' %}"></a>
                        </div>
                    </div>
                    <ul>
                        {% for tache in project.tache_set.all %}
                        <li>
                            <form action="{% url 'projects:update-tache' tache.id %}" id="form-tache-{{ tache.id }}" data-tache-id="{{ tache.id }}">
                                {% csrf_token %}
                                <input type="checkbox" id="item-{{ tache.id}}" name="checked" {% if tache.checked %}checked{% endif %}>
                                <label for="item-{{ tache.id}}" class="text">{{ tache.description }}</label>
                                <label for="item-{{ tache.id}}" class="button"></label>
                                <div class="wrapper">
                                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 98.5 98.5" enable-background="new 0 0 98.5 98.5" xml:space="preserve">
                                        <path class="checkmark" fill="none" stroke-width="8" stroke-miterlimit="10" d="M81.7,17.8C73.5,9.3,62,4,49.2,4
                                        C24.3,4,4,24.3,4,49.2s20.3,45.2,45.2,45.2s45.2-20.3,45.2-45.2c0-8.6-2.4-16.6-6.5-23.4l0,0L45.6,68.2L24.7,47.3"/>
                                    </svg>
                                </div>
                            </form>
                        </li>
                        {% endfor %}
                        {% if project.tache_set.all|length == 0 %}
                        <li>
                            Pas encore de tâche
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="col-lg-4">
            <div class="frame m-2">
                <div class="add-project">
                    <a href="{% url 'projects:add-project' %}"><img src="{% static 'images/plus.png' %}"></a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

projects/templates/projects/login.html
{% extends 'projects/base.html' %}
{% block title %}Accueil{% endblock %}
{% block navbar %}{% endblock %}
{% block content %}
{% load static %}
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-7 col-lg-5">
					<div class="wrap">
						<div class="login-wrap p-4 p-md-5">
							<div class="d-flex">
								<div class="w-100">
									<h3 class="mb-4">Connectez-vous</h3>
								</div>
							</div>
							<form action="#" class="signin-form" method="post">
								{% csrf_token %}

								<div class="form-group mt-3">
									<input id="username" type="text" name="username" class="form-control" required>
									<label class="form-control-placeholder" for="username">Nom d'utilisateur</label>
								</div>
								<div class="form-group">
								  <input id="password-field" type="password" name="password" class="form-control" required>
								  <label class="form-control-placeholder" for="password-field">Mot de passe</label>
								  <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
								</div>
								<div class="form-group">
									<button type="submit" class="form-control btn btn-login rounded submit px-3">Se connecter</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

projects/templates/projects/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>